import type { Metadata } from "next";
import {Ubuntu} from "next/font/google";
import "./globals.css";
import React from "react";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ["300", "400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="bg-magnolia" lang="en">
      <body className={ubuntu.className}>{children}</body>
    </html>
  );
}
