export enum Logos {
    Github = "/assets/images/icon-github.svg",
    FrontendMentor = "/assets/images/icon-frontend-mentor.svg",
    Twitter = "/assets/images/icon-twitter.svg",
    LinkedIn = "/assets/images/icon-linkedin.svg",
    YouTube = "/assets/images/icon-youtube.svg",
    Facebook = "/assets/images/icon-facebook.svg",
    Twitch = "/assets/images/icon-twitch.svg",
    Devto = "/assets/images/icon-devto.svg",
    Codewars = "/assets/images/icon-codewars.svg",
    Codepen = "/assets/images/icon-codepen.svg",
    freeCodeCamp = "/assets/images/icon-freecodecamp.svg",
    GitLab = "/assets/images/icon-gitlab.svg",
    Hashnode = "/assets/images/icon-hashnode.svg",
    StackOverflow = "/assets/images/icon-stack-overflow.svg",
}

export enum Colors {
    Github = "#191919",
    FrontendMentor = "#FDFDFD",
    Twitter = "#44B7E9",
    LinkedIn = "#2D68FF",
    YouTube = "#EE3837",
    Facebook = "#2441AC",
    Twitch = "#EE3FC8",
    Devto = "#373737",
    Codewars = "#8C1E53",
    Codepen = "#AE2241",
    freeCodeCamp = "#34276A",
    GitLab = "#EA4D2A",
    Hashnode = "#0934D0",
    StackOverflow = "#EB7306",
}