export enum Logos {
    Github = "/assets/images/icon-github.svg",
    FrontendMentor = "/assets/images/icon-frontend-mentor.svg",
    Twitter = "/assets/images/icon-twitter.svg",
    LinkedIn = "/assets/images/icon-linkedin.svg",
    YouTube = "/assets/images/icon-youtube.svg",
    Facebook = "/assets/images/icon-facebook.svg",
    Twitch = "/assets/images/icon-twitch.svg",
    Devto = "/assets/images/icon-devto.svg",
    Codewars = "/assets/images/icon-codewars.svg",
    Codepen = "/assets/images/icon-codepen.svg",
    freeCodeCamp = "/assets/images/icon-freecodecamp.svg",
    GitLab = "/assets/images/icon-gitlab.svg",
    Hashnode = "/assets/images/icon-hashnode.svg",
    StackOverflow = "/assets/images/icon-stack-overflow.svg",
}

export enum Colors {
    Github = "#191919",
    FrontendMentor = "#FDFDFD",
    Twitter = "#44B7E9",
    LinkedIn = "#2D68FF",
    YouTube = "#EE3837",
    Facebook = "#2441AC",
    Twitch = "#EE3FC8",
    Devto = "#373737",
    Codewars = "#8C1E53",
    Codepen = "#AE2241",
    freeCodeCamp = "#34276A",
    GitLab = "#EA4D2A",
    Hashnode = "#0934D0",
    StackOverflow = "#EB7306",
}

export enum PlaceholderLinks {
    Github = "e.g. https://www.github.com",
    FrontendMentor = "e.g. https://www.frontendmentor.com",
    Twitter = "e.g. https://www.twitter.com",
    LinkedIn = "e.g. https://www.linkedin.com",
    YouTube = "e.g. https://www.youtube.com",
    Facebook = "e.g. https://www.facebook.com",
    Twitch = "e.g. https://www.twitch.com",
    Devto = "e.g. https://www.devto.com",
    Codewars = "e.g. https://www.codewars.com",
    Codepen = "e.g. https://www.codepen.com",
    freeCodeCamp = "e.g. https://www.freecodecamp.com",
    GitLab = "e.g. https://www.gitlab.com",
    Hashnode = "e.g. https://www.hashnode.com",
    StackOverflow = "e.g. https://www.stackoverflow.com",
}