import type { Metadata } from "next";
import "./globals.css";
import {barlow, barlowCondensed, bellefair} from "@/app/fonts";
import Header from "@/app/_components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.variable} ${bellefair.variable} ${barlowCondensed.variable} min-h-screen bg-destination-mobile tablet:bg-destination-tablet desktop:bg-destination-desktop bg-no-repeat bg-cover bg-bottom desktop:bg-right flex flex-col h-full`}>
          <Header/>
          {children}
      </body>
    </html>
  );
}
